### ISSUE TITLE
'geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by Rahulsunny11** [bellalMohamed/fb-pages-likes-scraper#1]
Hi, I tried running your tool in my system but i am getting 'geckodriver' executable needs to be in PATH.
I have downloaded geckodriver and added it in the path but still i am getting the same error. Please help me with this

> Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scrape.py", line 7, in <module>
    init_driver()
  File "C:\Users\ADMIN\Downloads\Compressed\fb-pages-likes-scraper-master\helpers.py", line 25, in init_driver
    driver = webdriver.Firefox(options=options)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by bellalMohamed** [comment]
You can edit the helpers script and add the executable_path directly, like this


```
webdriver.Firefox(executable_path=r'your\path\geckodriver.exe')

```

**Comment by Rahulsunny11** [comment]
great, thank you. It is working but 

> driver.get('https://web.facebook.com/search/str/'+ str(pageId) +'/likers')

is showing page not found error in browser

**Comment by Rahulsunny11** [comment]
also cmd is showing this error 

> NameError: name 'sleep' is not defined

**Comment by bellalMohamed** [comment]
> great, thank you. It is working but
> 
> > driver.get('https://web.facebook.com/search/str/'+ str(pageId) +'/likers')
> 
> is showing page not found error in browser

I think this method is not working any more as FB removed the ```/search/str/{pageId}/likers```

**Comment by Rahulsunny11** [comment]
> > great, thank you. It is working but
> > > driver.get('https://web.facebook.com/search/str/'+ str(pageId) +'/likers')
> > 
> > 
> > is showing page not found error in browser
> 
> I think this method is not working any more as FB removed the `/search/str/{pageId}/likers`

is there any other alternative?

**Comment by Rahulsunny11** [comment]
I also have to scrape no of followers and likes for a page.. can you help me with this?
thank you
